In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("Omnichannel Retail Data.csv")

In [5]:
df.head()

,Product ID,Product Name,Category,Date,Online Store Location,Sales Quantity,Selling Price,Promotions,Demand Trend,Customer Segments,...,Stockout Frequency,Reorder Point,Order Fulfillment Time (days),Retail Store Location,Market Price,Competitor Prices,Discounts,Sales Volume,Return Rate (%),Elasticity Index
0,4277,Refrigerator,Home Appliances,2024-01-03,Mumbai,330,24.38,No,Increasing,Regular,...,10,19,8,Bangalore,31.25,54.64,22.15,207,18.61,1.28
1,5406,Mixer,Home Appliances,2024-01-11,Kolkata,429,24.83,Yes,Decreasing,Premium,...,10,128,6,Mumbai,10.22,14.24,40.19,268,17.19,2.23
2,5617,T-Shirt,Fashion,2024-04-04,Ahmedabad,298,13.41,No,Stable,Regular,...,17,195,9,Ahmedabad,87.52,54.64,49.52,328,15.77,1.79
3,5617,T-Shirt,Fashion,2024-04-04,Ahmedabad,298,13.41,No,Stable,Regular,...,12,42,1,Ahmedabad,87.52,54.64,49.52,328,15.77,1.79
4,7315,Jeans,Fashion,2024-11-25,Chennai,336,59.54,Yes,Stable,Premium,...,11,69,11,Hyderabad,86.49,16.88,11.80,428,14.80,0.51

In [6]:
df.shape

(12880, 22)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12880 entries, 0 to 12879
Data columns (total 22 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Product ID                     12880 non-null  int64
 1   Product Name                   12880 non-null  object
 2   Category                       12880 non-null  object
 3   Date                           12880 non-null  object
 4   Online Store Location          12880 non-null  object
 5   Sales Quantity                 12880 non-null  int64
 6   Selling Price                  12880 non-null  float64
 7   Promotions                     12880 non-null  object
 8   Demand Trend                   12880 non-null  object
 9   Customer Segments              12880 non-null  object
 10  Warehouse Location             12880 non-null  object
 11  Stock Levels                   12880 non-null  int64
 12  Stockout Frequency             12880 non-null  int64
 13  Reorder Point                  12880 non-null  int64
 14  Order Fulfillment Time (days)  12880 non-null  int64
 15  Retail Store Location          12880 non-null  object
 16  Market Price                   12880 non-null  float64
 17  Competitor Prices              12880 non-null  float64
 18  Discounts                      12880 non-null  float64
 19  Sales Volume                   12880 non-null  int64
 20  Return Rate (%)                12880 non-null  float64
 21  Elasticity Index               12880 non-null  float64
dtypes: float64(6), int64(7), object(9)
memory usage: 2.2+ MB

In [8]:
df.describe()

,Product ID,Sales Quantity,Selling Price,Stock Levels,Stockout Frequency,Reorder Point,Order Fulfillment Time (days),Market Price,Competitor Prices,Discounts,Sales Volume,Return Rate (%),Elasticity Index
count,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000
mean,5568.397438,250.862345,52.653249,504.406056,9.432609,104.993556,7.462578,52.966769,52.486540,25.262783,245.208618,9.958283,1.502849
std,2551.603244,144.492031,27.576372,290.195012,5.828538,55.506320,4.012133,27.221748,27.312972,14.515641,144.012953,5.797089,0.577084
min,1000.000000,1.000000,5.010000,0.000000,0.000000,10.000000,1.000000,5.030000,5.020000,0.020000,1.000000,0.010000,0.500000
25%,3388.500000,126.000000,28.260000,255.000000,4.000000,57.000000,4.000000,30.102500,28.960000,12.700000,123.000000,4.850000,1.010000
50%,5684.000000,250.000000,52.330000,497.000000,9.000000,106.000000,7.000000,53.150000,52.270000,25.080000,240.000000,10.060000,1.500000
75%,7744.000000,376.000000,76.660000,757.000000,14.000000,153.000000,11.000000,76.900000,75.575000,37.920000,367.250000,14.930000,1.990000
max,9998.000000,499.000000,99.980000,999.000000,19.000000,199.000000,14.000000,99.990000,99.990000,49.970000,499.000000,20.000000,2.500000

In [ ]:
#Checking Missing Values

In [9]:
df.isnull().sum()

Product ID                       0
Product Name                     0
Category                         0
Date                             0
Online Store Location            0
Sales Quantity                   0
Selling Price                    0
Promotions                       0
Demand Trend                     0
Customer Segments                0
Warehouse Location               0
Stock Levels                     0
Stockout Frequency               0
Reorder Point                    0
Order Fulfillment Time (days)    0
Retail Store Location            0
Market Price                     0
Competitor Prices                0
Discounts                        0
Sales Volume                     0
Return Rate (%)                  0
Elasticity Index                 0
dtype: int64

In [ ]:
#Removing Duplicate Values

In [10]:
df = df.drop_duplicates()

In [11]:
df.shape

(12880, 22)

In [ ]:
#Checking Inconsistent Values

In [12]:
df.nunique()

Product ID                       2780
Product Name                       25
Category                            5
Date                              365
Online Store Location               8
Sales Quantity                    499
Selling Price                    3641
Promotions                          2
Demand Trend                        3
Customer Segments                   3
Warehouse Location                  8
Stock Levels                      986
Stockout Frequency                 20
Reorder Point                     190
Order Fulfillment Time (days)      14
Retail Store Location               8
Market Price                     3636
Competitor Prices                3634
Discounts                        2986
Sales Volume                      499
Return Rate (%)                  1774
Elasticity Index                  201
dtype: int64

In [13]:
for col in df.select_dtypes(include='object').columns:
    print(col)
    print(df[col].unique())

Product Name
['Refrigerator' 'Mixer' 'T-Shirt' 'Jeans' 'Bookshelf' 'Laptop' 'Fan'
 'Keyboard' 'Monitor' 'Sofa' 'Desk' 'Rice' 'Snacks' 'Sneakers' 'Milk'
 'Hoodie' 'Chair' 'Washing Machine' 'Microwave' 'Table' 'Coffee' 'Bread'
 'Smartphone' 'Jacket' 'Headphones']
Category
['Home Appliances' 'Fashion' 'Furniture' 'Electronics' 'Groceries']
Date
['2024-01-03' '2024-01-11' '2024-04-04' '2024-11-25' '2024-11-13'
 '2024-10-25' '2024-05-13' '2024-04-01' '2024-07-06' '2024-05-10'
 '2024-03-09' '2024-12-24' '2024-12-09' '2024-11-29' '2024-05-18'
 '2024-08-23' '2024-01-22' '2024-07-31' '2024-09-01' '2024-03-17'
 '2024-02-26' '2024-08-27' '2024-06-14' '2024-04-06' '2024-02-02'
 '2024-03-23' '2024-08-18' '2024-10-15' '2024-01-06' '2024-09-05'
 '2024-11-30' '2024-11-07' '2024-04-25' '2024-07-25' '2024-10-01'
 '2024-10-27' '2024-01-09' '2024-04-30' '2024-03-10' '2024-06-24'
 '2024-04-17' '2024-06-20' '2024-07-21' '2024-01-15' '2024-02-01'
 '2024-05-01' '2024-04-12' '2024-05-29' '2024-11-03' '2024-08-04'
 '2024-02-05' '2024-11-20' '2024-03-08' '2024-07-09' '2024-12-11'
 '2024-06-29' '2024-12-05' '2024-03-07' '2024-01-24' '2024-11-24'
 '2024-07-02' '2024-07-14' '2024-05-08' '2024-03-29' '2024-10-12'
 '2024-10-26' '2024-10-09' '2024-09-27' '2024-08-02' '2024-10-23'
 '2024-03-24' '2024-03-16' '2024-05-21' '2024-06-01' '2024-10-19'
 '2024-09-04' '2024-08-20' '2024-10-28' '2024-11-17' '2024-06-23'
 '2024-04-22' '2024-02-23' '2024-08-21' '2024-08-13' '2024-08-14'
 '2024-12-10' '2024-08-10' '2024-11-09' '2024-02-12' '2024-02-25'
 '2024-07-11' '2024-08-25' '2024-11-14' '2024-07-08' '2024-02-16'
 '2024-01-26' '2024-12-21' '2024-06-05' '2024-10-04' '2024-01-19'
 '2024-10-24' '2024-03-18' '2024-01-27' '2024-02-20' '2024-05-31'
 '2024-11-18' '2024-10-03' '2024-05-07' '2024-10-11' '2024-10-02'
 '2024-09-02' '2024-12-20' '2024-07-04' '2024-11-15' '2024-03-14'
 '2024-07-30' '2024-03-15' '2024-07-29' '2024-12-06' '2024-05-22'
 '2024-10-07' '2024-12-16' '2024-06-30' '2024-11-08' '2024-09-12'
 '2024-12-15' '2024-08-05' '2024-04-18' '2024-12-23' '2024-05-28'
 '2024-02-19' '2024-04-02' '2024-09-08' '2024-08-24' '2024-06-13'
 '2024-03-05' '2024-12-07' '2024-03-02' '2024-03-27' '2024-02-29'
 '2024-06-02' '2024-11-02' '2024-02-13' '2024-06-17' '2024-04-23'
 '2024-12-26' '2024-05-15' '2024-01-02' '2024-09-10' '2024-12-22'
 '2024-01-28' '2024-01-25' '2024-02-08' '2024-02-10' '2024-05-25'
 '2024-07-15' '2024-11-05' '2024-09-19' '2024-08-09' '2024-05-30'
 '2024-05-12' '2024-01-17' '2024-07-23' '2024-05-06' '2024-02-07'
 '2024-09-15' '2024-04-16' '2024-01-31' '2024-02-17' '2024-07-12'
 '2024-01-23' '2024-06-22' '2024-05-05' '2024-03-22' '2024-04-09'
 '2024-05-03' '2024-08-12' '2024-01-13' '2024-06-08' '2024-11-28'
 '2024-05-27' '2024-09-28' '2024-06-15' '2024-09-26' '2024-12-18'
 '2024-12-28' '2024-04-24' '2024-02-18' '2024-07-24' '2024-12-04'
 '2024-05-11' '2024-08-22' '2024-06-16' '2024-09-16' '2024-12-03'
 '2024-03-12' '2024-11-26' '2024-04-28' '2024-02-14' '2024-08-15'
 '2024-10-08' '2024-09-13' '2024-08-01' '2024-10-06' '2024-06-04'
 '2024-07-16' '2024-07-18' '2024-07-07' '2024-04-26' '2024-03-13'
 '2024-06-27' '2024-03-20' '2024-07-10' '2024-09-09' '2024-07-26'
 '2024-09-18' '2024-06-21' '2024-09-25' '2024-01-05' '2024-12-29'
 '2024-09-03' '2024-04-10' '2024-11-01' '2024-02-22' '2024-11-04'
 '2024-05-04' '2024-01-21' '2024-12-30' '2024-10-29' '2024-04-15'
 '2024-04-29' '2024-01-01' '2024-02-21' '2024-05-09' '2024-12-12'
 '2024-08-30' '2024-08-17' '2024-04-08' '2024-05-20' '2024-05-23'
 '2024-06-03' '2024-04-14' '2024-03-11' '2024-06-25' '2024-08-28'
 '2024-11-19' '2024-10-22' '2024-04-19' '2024-08-08' '2024-06-12'
 '2024-09-20' '2024-08-26' '2024-10-30' '2024-08-29' '2024-10-10'
 '2024-12-14' '2024-04-20' '2024-03-31' '2024-04-13' '2024-02-09'
 '2024-05-14' '2024-10-18' '2024-02-15' '2024-12-25' '2024-02-24'
 '2024-01-29' '2024-07-01' '2024-10-20' '2024-06-09' '2024-12-17'
 '2024-03-03' '2024-10-13' '2024-09-14' '2024-06-19' '2024-07-22'
 '2024-10-31' '2024-09-30' '2024-04-21' '2024-06-10' '2024-03-01'
 '2024-01-30' '2024-07-03' '2024-07-20' '2024-09-06' '2024-08-11'
 '2024-07-28' '2024-03-06' '2024-07-17' '2024-04-05' '2024-05-16'
 '2024-09-11' '2024-03-28' '2024-02-27' '2024-03-21' '2024-08-19'
 '2024-01-20' '2024-10-21' '2024-07-13' '2024-04-07' '2024-11-16'
 '2024-01-07' '2024-11-06' '2024-02-28' '2024-07-27' '2024-06-26'
 '2024-08-07' '2024-05-19' '2024-01-18' '2024-06-18' '2024-01-08'
 '2024-04-27' '2024-01-14' '2024-09-29' '2024-08-16' '2024-10-17'
 '2024-05-17' '2024-03-19' '2024-01-10' '2024-02-03' '2024-11-10'
 '2024-11-11' '2024-03-25' '2024-04-11' '2024-04-03' '2024-02-11'
 '2024-01-04' '2024-06-07' '2024-08-06' '2024-12-08' '2024-09-22'
 '2024-01-12' '2024-12-27' '2024-05-02' '2024-11-21' '2024-12-01'
 '2024-11-27' '2024-12-02' '2024-06-06' '2024-09-17' '2024-08-31'
 '2024-11-12' '2024-06-11' '2024-08-03' '2024-11-22' '2024-06-28'
 '2024-10-16' '2024-10-05' '2024-11-23' '2024-09-23' '2024-05-26'
 '2024-03-26' '2024-07-05' '2024-03-30' '2024-02-06' '2024-09-24'
 '2024-09-07' '2024-02-04' '2024-01-16' '2024-07-19' '2024-12-19'
 '2024-10-14' '2024-03-04' '2024-12-13' '2024-09-21' '2024-05-24']
Online Store Location
['Mumbai' 'Kolkata' 'Ahmedabad' 'Chennai' 'Delhi' 'Bangalore' 'Pune'
 'Hyderabad']
Promotions
['No' 'Yes']
Demand Trend
['Increasing' 'Decreasing' 'Stable']
Customer Segments
['Regular' 'Premium' 'Budget']
Warehouse Location
['Chennai' 'Kolkata' 'Pune' 'Delhi' 'Bangalore' 'Hyderabad' 'Ahmedabad'
 'Mumbai']
Retail Store Location
['Bangalore' 'Mumbai' 'Ahmedabad' 'Hyderabad' 'Delhi' 'Chennai' 'Kolkata'
 'Pune']

In [ ]:
#Handling Missing Values

In [14]:
df.fillna(0, inplace=True)

In [ ]:
#Detecting Outliers

In [15]:
numeric_cols = df.select_dtypes(include=np.number).columns
numeric_cols

Index(['Product ID', 'Sales Quantity', 'Selling Price', 'Stock Levels',
       'Stockout Frequency', 'Reorder Point', 'Order Fulfillment Time (days)',
       'Market Price', 'Competitor Prices', 'Discounts', 'Sales Volume',
       'Return Rate (%)', 'Elasticity Index'],
      dtype='object')

In [16]:
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(col, len(outliers))

Product ID 0
Sales Quantity 0
Selling Price 0
Stock Levels 0
Stockout Frequency 0
Reorder Point 0
Order Fulfillment Time (days) 0
Market Price 0
Competitor Prices 0
Discounts 0
Sales Volume 0
Return Rate (%) 0
Elasticity Index 0

In [17]:
# Fixing incorrect data types
df['Date'] = pd.to_datetime(df['Date'])

In [20]:
# Converting numeric columns
df['Sales Volume'] = df['Sales Volume'].astype(float)

In [21]:
# Standardizing column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [22]:
# Formatting categorical values
df['category'] = df['category'].str.title()

In [23]:
# Formatting date column
df['date'] = df['date'].dt.strftime('%Y-%m-%d')

In [24]:
# Checking unique categorical values
df['category'].unique()

array(['Home Appliances', 'Fashion', 'Furniture', 'Electronics',
       'Groceries'], dtype=object)

In [25]:
# Saving cleaned dataset
df.to_csv("Cleaned_Data.csv", index=False)